### PR TITLE
Added Kth Largest Element in an Array LeetCode question in Java

### PR DESCRIPTION
**Pull request by AkshatBhat**
Thanks for the oppoturnity. Please do merge it.

### CODE REVIEW

**Comment by afrozchakure** [comment]
Thanks for your pull request! 😄 

I think the following solution already exists in CPP, so try creating a new folder within `Medium` folder with name as the `ProblemName` and paste both the previous cpp solution and your own solution within it. 

Lookout for the proper camelcasing and naming the files & folder correctly.

**Comment by AkshatBhat** [comment]
Alright, will do so. Thanks!

**Comment by AkshatBhat** [comment]
Do I have to make another pull request?

**Comment by afrozchakure** [comment]
You may push to the same pull request.

**Comment by AkshatBhat** [comment]
I have done the needful. Please check it.

**Review by afrozchakure — COMMENTED** [review]
Well done

**Comment by afrozchakure** [comment]
fixes #46

**Comment by afrozchakure** [comment]
closes #46

**Pull request merged**
