### PR TITLE
Added Codewars problems and change in Readme

### PR DESCRIPTION
**Pull request by soham4abc**
3 codewars problems added along with Some geeksforgeeks problems.

### CODE REVIEW

**Comment by soham4abc** [comment]
There are 6 conflicts in README. It's same as of the latest merge.. Do have a look!

**Comment by afrozchakure** [comment]
You may have forgotten to do, ``git pull`` before making those changes.

#### Follow this

Instead of pushing via `master` branch directly, can you make a branch from `master` and then push this?

After creating a branch, checkout to that branch and do ``git fetch upstream`` & ``git pull upstream master``. 

Make the changes to the files, and then do ``git commit`` and ``git push``.

**Comment by soham4abc** [comment]
Yes why not!
It was my bad I forgot to pull. Will make a dev branch and will push to that .


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by soham4abc** [comment]
I am withdrawing  this pull request will make it all okay and issue another!

**Pull request closed without merging**
