### PR TITLE
day 0,1,2,3,13,27,28,29 solutions added

### PR DESCRIPTION
**Pull request by Snehakri022**
hackerrank 30 days of code (day 0,1,2,3,13,27,28,29) solutions added

### CODE REVIEW

**Comment by afrozchakure** [comment]
Thanks for contributing to this Repository @Snehakri022  :tada: :smile: 

Just a minor change, could you rename the files in the given format : ``Day_1_Problem_Name.cpp`` so that it is consistent with the repo files. You can find Problem names on top of Hackerrank problem statements. 

Screenshot from 2020-10-10 23-20-47

### Follow this
To edit the pull request, just push new changes into the same branch that was used for this pull request.

After this I'll merge your changes :100: :+1:

**Comment by Snehakri022** [comment]
I have renamed the files in the given format.

**Comment by Snehakri022** [comment]
I have  renamed the files in the given format.Please merge the changes.
Thanks and Regards

**Comment by afrozchakure** [comment]
Congratulations on the merge. Keep contributing :D :+1:

**Comment by afrozchakure** [comment]
@all-contributors please add @Snehakri022 for code

**Pull request merged**
