### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by anilkaundal**
Updated CONTRIBUTING.md

### CODE REVIEW

**Comment by afrozchakure** [comment]
@all-contributors please add @anilkaundal for code and doc

**Comment by afrozchakure** [comment]
Closes #11

**Comment by afrozchakure** [comment]
Thanks for the contributions @anilkaundal :tada: :smile:

**Comment by anilkaundal** [comment]
My pleasure. 🌻

**Pull request merged**
