### PR TITLE
write_a_function.py

### PR DESCRIPTION
**Pull request by Rupali409**
created a file in which An extra day is added to the calendar almost every four years as February 29, and the day is called a leap day. It corrects the calendar for the fact that our planet takes approximately 365.25 days to orbit the sun. A leap year contains a leap day.

In the Gregorian calendar, three conditions are used to identify leap years:

The year can be evenly divided by 4, is a leap year, unless:
The year can be evenly divided by 100, it is NOT a leap year, unless:
The year is also evenly divisible by 400. Then it is a leap year.
This means that in the Gregorian calendar, the years 2000 and 2400 are leap years, while 1800, 1900, 2100, 2200, 2300 and 2500 are NOT leap years. Source

Task

Given a year, determine whether it is a leap year. If it is a leap year, return the Boolean True, otherwise return False.

Note that the code stub provided reads from STDIN and passes arguments to the is_leap function. It is only necessary to complete the is_leap function.

### CODE REVIEW

**Comment by afrozchakure** [comment]
Thanks for contributing to this Repository @Rupali409   :tada: :smile: 

Just a minor change, could you rename the files in the given format : ``problem_name.py`` *(All Lowercase and separated by underscore)* so that it is consistent with the repo files. You can find Problem names on top of Hackerrank problem statements. 

Follow this format :
Screenshot from 2020-10-16 11-47-55

After this I'll merge your changes :100: :+1:

**Comment by Rupali409** [comment]
done can u please check.

**Comment by afrozchakure** [comment]
Thanks, but I actually wanted you to __make the suggested changes within your local copy and then push the code__ in the same branch which you used to make this pull request. ``Don't edit the title of this Pull request``

**Comment by afrozchakure** [comment]
@allcontributors add @Rupali409 for code

**Pull request merged**
